### ISSUE TITLE
Implementar CSS

### ISSUE THREAD

**Issue by Aleja-orju** [Aleja-orju/Fit_Wave_#1]
### Motivo
Mejorar la interfaz 

### Beneficios 
- Mejor visualización 
- Ayuda a los usuarios a navegar en el proyecto 
- Hacer más accesible el blog

**Comment by bragranav** [comment]
Se creo la siguiente rama: git checkout -b issue-implementarCSS

**Comment by Aleja-orju** [comment]
Se solucionó el problema entonces, se cerrará este issue. Muchas gracias.
